### ISSUE TITLE
Add option to turn off point reporting

### ISSUE THREAD

**Issue by WolfGangsta** [Boruch-Baum/emacs-xhair#2]
Hi, new to Emacs here, currently using DOOM Emacs.

Coming from NeoVim, I wanted to duplicate its crosshair functionality and came across `xhair`. It works fantastically--customizing `xhair-face` to `hl-line-face` makes it nice and unobtrusive, and adding `xhair-mode` to `prog-mode-hook` makes the crosshair start with no fuss when any code window opens, and disappear when the cursor leaves the window. Thank you for making this package available!

The only thing that I'd still like to do is keep `xhair` from writing anything to the minibuffer. I see that the `xhair-highlight` function includes a `nomsg` option, but I don't know how to activate it from `xhair-mode` itself. I guess `'msg` at [xhair.el:292](https://github.com/Boruch-Baum/emacs-xhair/blob/main/xhair.el#L292) must have something to do with it, but I don't know what.

I'd appreciate some advice! If there's some way to, say, override the `xhair--report-point` function from my DOOM Emacs config, that would be perfect. If there's no config solution, consider this a feature request for a new variable or something. Thanks for your patience.

Things I've tried adding to my .doom.d/packages.el, directly below `(package! xhair)`:
```elisp
(advice-add 'xhair--report-point :override
            (lambda () (message "will this override xhair--report-point?")))
```
```elisp
(with-eval-after-load "xhair"
  '(defun xhair--report-point ()
     "My override, should prevent xhair from reporting points to the buffer."
     nil))
```
Neither of these succeeded in overriding the function.

**Comment by Boruch-Baum** [comment]
Glad to hear that you're finding the package useful!

The two places that I see the package sending information to the
minibuffer are with function 'message' at lines 161 and 303.

Here are two suggestions:

1) You could just remove those 'message' function calls from your
   personal copy of the code. Remember that with lisp, you need to
   preserve the extra parentheses on those lines. For package 'xhair',
   this option is probably safe because the package has been sitting
   stable with no commits needed for more than three years.

2) You could write an advice AROUND each of the two functions that call
   the 'message' function. All the advice needs to do is create a scope
   (ie. 'let') and define Emacs variable 'inhibit-message' NON-NIL
   within it.

     (let ((inhibit-message t))
       .. call the advised function in your favorite way .. )

   I STRONGLY recommend NEVER using lambda functions for advices. Doing
   so creates difficulties in debugging, modifying, and removing
   advices.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by WolfGangsta** [comment]
Thank you for getting back so soon, Boruch!

I found out that some of my troubles were DOOM-specific--because I was trying to place my advice/overrides directly after `(package! xhair)` in `~/.doom.d/packages.el`. I guess whatever reads that file isn't the normal lisp reader, because nothing besides the `package!` statement I put in there has any effect on my EMACS. That detail must be in the documentation somewhere, but I haven't come across it.

I went ahead with your suggestion and defined a named function (instead of a lambda) in my config file at `~/.doom.d/config.el`:
```elisp
(defun mute-messages (orig-fun &rest args)
  "Used as advice around a function to mute its messages.
Does so by setting `inhibit-message' to `t' temporarily."
  (let ((inhibit-message t))
    (apply orig-fun args)))
```
(Not yet having a favorite way to call an advised function, I used the `apply` function as shown in the EMACS docs [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html), second from last code block.)

Directly beneath, I placed the advice around `xhair--report-point`:
```elisp
(advice-add 'xhair--report-point :around #'mute-messages)
```
(Right now I don't feel the need to override the other function that prints messages, `xhair-mode`.)

This got rid of the message--but with `xhair-mode` always on in my code buffers, `xhair-eldoc-idle-delay` was still overriding `eldoc-idle-delay` to 3.0 seconds, too long for my liking. I went ahead and customized `xhair-eldoc-idle-delay` to be 0.5 seconds, same as `eldoc-idle-delay` is for my config. That's got everything working the way I like it!

I have one more question, but it's only academic: is there a way to customize `xhair-eldoc-idle-delay` so that it always has the value of `eldoc-idle-delay`, even if the latter changes? Or better, how can one prevent `xhair-eldoc-idle-delay` from overriding `eldoc-idle-delay` at all, short of modifying the source? The Easy Customization GUI doesn't seem to allow binding one custom variable to the value of another like I seemed to be able to do with custom faces.

**Comment by Boruch-Baum** [comment]
On 2024-10-07 17:07, WolfGangsta wrote:
>    Thank you for getting back so soon, Boruch!

No Problem. Glad to be of help.

>    I have one more question, but it's only academic: is there a way to
>    customize xhair-eldoc-idle-delay so that it always has the value of
>    eldoc-idle-delay, even if the latter changes? Or better, how can one
>    prevent xhair-eldoc-idle-delay from overriding eldoc-idle-delay at all,
>    short of modifying the source? The Easy Customization GUI doesn't seem
>    to allow binding one custom variable to the value of another like I
>    seemed to be able to do with custom faces.

Maybe try redefining variable xhair-eldoc-idle-delay to be an alias of
eldoc-idle-delay?

If this closes your issue, please mark it as such.

Kind regards,

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by WolfGangsta** [comment]
Thank you, Boruch! "Alias" was the new word of the day for me, and exactly what I was looking for.

I put this line after my others in `~/.doom.d/config.el`:
```elisp
(after! xhair
  (defvaralias 'xhair-eldoc-idle-delay 'eldoc-idle-delay))
```

...and now `xhair-eldoc-idle-delay` simply means `eldoc-idle-delay`.

Closing the issue. Have a great day,
Owen
